spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080

app:
  name: todo list manager
  version: 2.0.0
  api-version: 2.0.0
  attachments:
    upload-dir: uploads


logging:
  level:
    root: INFO
    com.example.todolist: INFO
    org.springframework.web: WARN
