spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}



server:
  port: 8080

logging:
  level:
    com.example.todolist: DEBUG
    org.springframework.web: DEBUG


app:
  name: todo list manager
  version: 2.0.0
  api-version: 2.0.0
  attachments:
    upload-dir: uploads