spring.application.name=todo-list-manager
server.port=8080

logging.level.com.example.todolist=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.aop=DEBUG

logging.level.org.hibernate.SQL=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n